domain: louttche.github.io
base_url: ""

# Build settings
theme: jekyll-theme-cayman

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:slug/
    title: Projects
    description: A collection of my projects.

exclude:
  - _projects/project_template.md
  - local_assets