local_backend: true

backend:
  name: git-gateway # test-repo
  branch: main
media_folder: 'assets/images'
collections:
  - name: 'project'
    label: 'Project'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }