# Example: https://github.com/decaporg/decap-cms/blob/main/dev-test/config.yml

local_backend: true

backend:
  name: git-gateway # test-repo
  branch: main
media_folder: 'assets/images'
collections:
  - name: 'project'
    label: 'Project'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - name: "thumbnail"
        required: false
        label: "Cover image"
        widget: "image"
        choose_url: true
        media_folder: "/assets/images/{{slug}}"
        media_library:
          config:
            max_file_size: 512000
      - name: 'carousel_images'
        required: false
        label: "Carousel images"
        widget: 'image'
        choose_url: true
        media_folder: "/assets/images/{{slug}}/carousel"
        media_library:
          config:
            multiple: true
            max_files: 10
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'About Section'
        name: 'about'
        file: '_includes/about_me.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'navigation'
        file: '_data/sidebar_navigation.yml'
        fields:
          - label: 'Navigation Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }